// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.0
// source: pkg/proto/revocation/revocation.proto

package revocation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RevocationProofService_GetProof_FullMethodName  = "/revocation.RevocationProofService/GetProof"
	RevocationProofService_GetStatus_FullMethodName = "/revocation.RevocationProofService/GetStatus"
)

// RevocationProofServiceClient is the client API for RevocationProofService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RevocationProofServiceClient interface {
	GetProof(ctx context.Context, in *GetProofRequest, opts ...grpc.CallOption) (*GetProofResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
}

type revocationProofServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRevocationProofServiceClient(cc grpc.ClientConnInterface) RevocationProofServiceClient {
	return &revocationProofServiceClient{cc}
}

func (c *revocationProofServiceClient) GetProof(ctx context.Context, in *GetProofRequest, opts ...grpc.CallOption) (*GetProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProofResponse)
	err := c.cc.Invoke(ctx, RevocationProofService_GetProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *revocationProofServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, RevocationProofService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RevocationProofServiceServer is the server API for RevocationProofService service.
// All implementations must embed UnimplementedRevocationProofServiceServer
// for forward compatibility.
type RevocationProofServiceServer interface {
	GetProof(context.Context, *GetProofRequest) (*GetProofResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	mustEmbedUnimplementedRevocationProofServiceServer()
}

// UnimplementedRevocationProofServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRevocationProofServiceServer struct{}

func (UnimplementedRevocationProofServiceServer) GetProof(context.Context, *GetProofRequest) (*GetProofResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProof not implemented")
}
func (UnimplementedRevocationProofServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedRevocationProofServiceServer) mustEmbedUnimplementedRevocationProofServiceServer() {
}
func (UnimplementedRevocationProofServiceServer) testEmbeddedByValue() {}

// UnsafeRevocationProofServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RevocationProofServiceServer will
// result in compilation errors.
type UnsafeRevocationProofServiceServer interface {
	mustEmbedUnimplementedRevocationProofServiceServer()
}

func RegisterRevocationProofServiceServer(s grpc.ServiceRegistrar, srv RevocationProofServiceServer) {
	// If the following call panics, it indicates UnimplementedRevocationProofServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RevocationProofService_ServiceDesc, srv)
}

func _RevocationProofService_GetProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevocationProofServiceServer).GetProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RevocationProofService_GetProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevocationProofServiceServer).GetProof(ctx, req.(*GetProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RevocationProofService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevocationProofServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RevocationProofService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevocationProofServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RevocationProofService_ServiceDesc is the grpc.ServiceDesc for RevocationProofService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RevocationProofService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "revocation.RevocationProofService",
	HandlerType: (*RevocationProofServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProof",
			Handler:    _RevocationProofService_GetProof_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _RevocationProofService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/revocation/revocation.proto",
}
