// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/proto/revocation/revocation.proto

package revocation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuerId      string                 `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProofRequest) Reset() {
	*x = GetProofRequest{}
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofRequest) ProtoMessage() {}

func (x *GetProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofRequest.ProtoReflect.Descriptor instead.
func (*GetProofRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_revocation_revocation_proto_rawDescGZIP(), []int{0}
}

func (x *GetProofRequest) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *GetProofRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

type IndexedLeaf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	NextValue     string                 `protobuf:"bytes,2,opt,name=next_value,json=nextValue,proto3" json:"next_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexedLeaf) Reset() {
	*x = IndexedLeaf{}
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexedLeaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexedLeaf) ProtoMessage() {}

func (x *IndexedLeaf) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexedLeaf.ProtoReflect.Descriptor instead.
func (*IndexedLeaf) Descriptor() ([]byte, []int) {
	return file_pkg_proto_revocation_revocation_proto_rawDescGZIP(), []int{1}
}

func (x *IndexedLeaf) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *IndexedLeaf) GetNextValue() string {
	if x != nil {
		return x.NextValue
	}
	return ""
}

type GetProofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuerId      string                 `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	ProofType     uint32                 `protobuf:"varint,3,opt,name=proof_type,json=proofType,proto3" json:"proof_type,omitempty"`
	Root          string                 `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Leaf          *IndexedLeaf           `protobuf:"bytes,6,opt,name=leaf,proto3" json:"leaf,omitempty"`
	LeafIndex     uint64                 `protobuf:"varint,7,opt,name=leaf_index,json=leafIndex,proto3" json:"leaf_index,omitempty"`
	Siblings      []string               `protobuf:"bytes,8,rep,name=siblings,proto3" json:"siblings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProofResponse) Reset() {
	*x = GetProofResponse{}
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofResponse) ProtoMessage() {}

func (x *GetProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofResponse.ProtoReflect.Descriptor instead.
func (*GetProofResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_revocation_revocation_proto_rawDescGZIP(), []int{2}
}

func (x *GetProofResponse) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *GetProofResponse) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *GetProofResponse) GetProofType() uint32 {
	if x != nil {
		return x.ProofType
	}
	return 0
}

func (x *GetProofResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *GetProofResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetProofResponse) GetLeaf() *IndexedLeaf {
	if x != nil {
		return x.Leaf
	}
	return nil
}

func (x *GetProofResponse) GetLeafIndex() uint64 {
	if x != nil {
		return x.LeafIndex
	}
	return 0
}

func (x *GetProofResponse) GetSiblings() []string {
	if x != nil {
		return x.Siblings
	}
	return nil
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_revocation_revocation_proto_rawDescGZIP(), []int{3}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Generations   map[string]*IssuerStatus `protobuf:"bytes,1,rep,name=generations,proto3" json:"generations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UptimeSeconds float64                  `protobuf:"fixed64,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_revocation_revocation_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatusResponse) GetGenerations() map[string]*IssuerStatus {
	if x != nil {
		return x.Generations
	}
	return nil
}

func (x *GetStatusResponse) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type IssuerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loaded        bool                   `protobuf:"varint,1,opt,name=loaded,proto3" json:"loaded,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	LeafCount     int32                  `protobuf:"varint,3,opt,name=leaf_count,json=leafCount,proto3" json:"leaf_count,omitempty"`
	Depth         int32                  `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`
	Root          string                 `protobuf:"bytes,5,opt,name=root,proto3" json:"root,omitempty"`
	CrlNumber     uint64                 `protobuf:"varint,6,opt,name=crl_number,json=crlNumber,proto3" json:"crl_number,omitempty"`
	LoadedAt      string                 `protobuf:"bytes,7,opt,name=loaded_at,json=loadedAt,proto3" json:"loaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuerStatus) Reset() {
	*x = IssuerStatus{}
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuerStatus) ProtoMessage() {}

func (x *IssuerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuerStatus.ProtoReflect.Descriptor instead.
func (*IssuerStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_revocation_revocation_proto_rawDescGZIP(), []int{5}
}

func (x *IssuerStatus) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *IssuerStatus) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *IssuerStatus) GetLeafCount() int32 {
	if x != nil {
		return x.LeafCount
	}
	return 0
}

func (x *IssuerStatus) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *IssuerStatus) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *IssuerStatus) GetCrlNumber() uint64 {
	if x != nil {
		return x.CrlNumber
	}
	return 0
}

func (x *IssuerStatus) GetLoadedAt() string {
	if x != nil {
		return x.LoadedAt
	}
	return ""
}

var File_pkg_proto_revocation_revocation_proto protoreflect.FileDescriptor

const file_pkg_proto_revocation_revocation_proto_rawDesc = "" +
	"\n" +
	"%pkg/proto/revocation/revocation.proto\x12\n" +
	"revocation\"S\n" +
	"\x0fGetProofRequest\x12\x1b\n" +
	"\tissuer_id\x18\x01 \x01(\tR\bissuerId\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\"B\n" +
	"\vIndexedLeaf\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"next_value\x18\x02 \x01(\tR\tnextValue\"\x85\x02\n" +
	"\x10GetProofResponse\x12\x1b\n" +
	"\tissuer_id\x18\x01 \x01(\tR\bissuerId\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x1d\n" +
	"\n" +
	"proof_type\x18\x03 \x01(\rR\tproofType\x12\x12\n" +
	"\x04root\x18\x04 \x01(\tR\x04root\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12+\n" +
	"\x04leaf\x18\x06 \x01(\v2\x17.revocation.IndexedLeafR\x04leaf\x12\x1d\n" +
	"\n" +
	"leaf_index\x18\a \x01(\x04R\tleafIndex\x12\x1a\n" +
	"\bsiblings\x18\b \x03(\tR\bsiblings\"\x12\n" +
	"\x10GetStatusRequest\"\xe6\x01\n" +
	"\x11GetStatusResponse\x12P\n" +
	"\vgenerations\x18\x01 \x03(\v2..revocation.GetStatusResponse.GenerationsEntryR\vgenerations\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x01R\ruptimeSeconds\x1aX\n" +
	"\x10GenerationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.revocation.IssuerStatusR\x05value:\x028\x01\"\xbf\x01\n" +
	"\fIssuerStatus\x12\x16\n" +
	"\x06loaded\x18\x01 \x01(\bR\x06loaded\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x1d\n" +
	"\n" +
	"leaf_count\x18\x03 \x01(\x05R\tleafCount\x12\x14\n" +
	"\x05depth\x18\x04 \x01(\x05R\x05depth\x12\x12\n" +
	"\x04root\x18\x05 \x01(\tR\x04root\x12\x1d\n" +
	"\n" +
	"crl_number\x18\x06 \x01(\x04R\tcrlNumber\x12\x1b\n" +
	"\tloaded_at\x18\a \x01(\tR\bloadedAt2\xa9\x01\n" +
	"\x16RevocationProofService\x12E\n" +
	"\bGetProof\x12\x1b.revocation.GetProofRequest\x1a\x1c.revocation.GetProofResponse\x12H\n" +
	"\tGetStatus\x12\x1c.revocation.GetStatusRequest\x1a\x1d.revocation.GetStatusResponseBGZEgithub.com/moven0831/moica-revocation-smt/server/pkg/proto/revocationb\x06proto3"

var (
	file_pkg_proto_revocation_revocation_proto_rawDescOnce sync.Once
	file_pkg_proto_revocation_revocation_proto_rawDescData []byte
)

func file_pkg_proto_revocation_revocation_proto_rawDescGZIP() []byte {
	file_pkg_proto_revocation_revocation_proto_rawDescOnce.Do(func() {
		file_pkg_proto_revocation_revocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_revocation_revocation_proto_rawDesc), len(file_pkg_proto_revocation_revocation_proto_rawDesc)))
	})
	return file_pkg_proto_revocation_revocation_proto_rawDescData
}

var file_pkg_proto_revocation_revocation_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_revocation_revocation_proto_goTypes = []any{
	(*GetProofRequest)(nil),   // 0: revocation.GetProofRequest
	(*IndexedLeaf)(nil),       // 1: revocation.IndexedLeaf
	(*GetProofResponse)(nil),  // 2: revocation.GetProofResponse
	(*GetStatusRequest)(nil),  // 3: revocation.GetStatusRequest
	(*GetStatusResponse)(nil), // 4: revocation.GetStatusResponse
	(*IssuerStatus)(nil),      // 5: revocation.IssuerStatus
	nil,                       // 6: revocation.GetStatusResponse.GenerationsEntry
}
var file_pkg_proto_revocation_revocation_proto_depIdxs = []int32{
	1, // 0: revocation.GetProofResponse.leaf:type_name -> revocation.IndexedLeaf
	6, // 1: revocation.GetStatusResponse.generations:type_name -> revocation.GetStatusResponse.GenerationsEntry
	5, // 2: revocation.GetStatusResponse.GenerationsEntry.value:type_name -> revocation.IssuerStatus
	0, // 3: revocation.RevocationProofService.GetProof:input_type -> revocation.GetProofRequest
	3, // 4: revocation.RevocationProofService.GetStatus:input_type -> revocation.GetStatusRequest
	2, // 5: revocation.RevocationProofService.GetProof:output_type -> revocation.GetProofResponse
	4, // 6: revocation.RevocationProofService.GetStatus:output_type -> revocation.GetStatusResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_revocation_revocation_proto_init() }
func file_pkg_proto_revocation_revocation_proto_init() {
	if File_pkg_proto_revocation_revocation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_revocation_revocation_proto_rawDesc), len(file_pkg_proto_revocation_revocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_revocation_revocation_proto_goTypes,
		DependencyIndexes: file_pkg_proto_revocation_revocation_proto_depIdxs,
		MessageInfos:      file_pkg_proto_revocation_revocation_proto_msgTypes,
	}.Build()
	File_pkg_proto_revocation_revocation_proto = out.File
	file_pkg_proto_revocation_revocation_proto_goTypes = nil
	file_pkg_proto_revocation_revocation_proto_depIdxs = nil
}
